### ISSUE TITLE
Missing piece of documentation and/or example

### ISSUE THREAD

**Issue by arthef** [shannah/CodeRAD#13]
CodeRAD and RADChatRoom are great additions to CN1 environment and API. I appreciate the effort and try to use them in my code.

However, I am having hard time to fully grasp CodeRAD concept. RADChatRoom component and tutorial is a very good description how to use it in complex scenarios. 

I am wondering what would be the best way to implement something as simple as user login form which shows when the user first opens the app and needs to enter account credentials. I guess this must be something rather simple like `FormController` with `EntityEditor`. I am sure I can create something based on the documentation, however, I am just not sure what is the best and most optimal way to do it using the library.

**Comment by shannah** [comment]
I am planning on creating a login component like you're describing, but got pulled away to focus on WebRTC.  You might be able to get some ideas from the TweetAppUIKit I've been working on, but haven't finished.

Some screenshots from the demo app can be seen here:
https://github.com/shannah/TweetAppUIKit/issues/1

You might be able to get some ideas by looking at the [views](https://github.com/shannah/TweetAppUIKit/tree/master/src/com/codename1/twitterui/views) as well as other classes.

A more direct example of a login form can be found in a side-project I was working on, which is a Codename One client for the old NovaServer BBS software.  

- [LoginFormViewModel](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/models/LoginFormViewModel.java)
- [LoginAction](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/schemas/LoginAction.java) - The schema defining tags used for the LoginViewModel.
- [LoginFormView](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/views/LoginFormView.java) 
- [LoginFormController](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/controllers/LoginFormController.java)

The early development stage of that side-project means that I haven't started working on making it "look nice".  I used an EntityEditor for the view to build it more quickly.  I'm not sure if I'll use that same approach when I create the login component for the TweetAppUIKit, or not.  That decision was made with high priority on getting it up and functional quickly - as opposed to building a long-term reusable component.

**Comment by arthef** [comment]
Thank you very much for all the details. I think this should be enough for me to get started.

**Comment by arthef** [comment]
Looked deeper and trying to adjust for my needs. Very neat code and concept.

I have one question though. 

In the [LoginFormController](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/controllers/LoginFormController.java) you open connection after username and password is entered. What would be the best way to handle an error here? I mean, the most common is user entering incorrect password. The `session.connect` in my case returns an error which I can handle accordingly and preferred way would be to show the form again with some additional information about mistake and how to correct it. Allow user to enter the password again.

Any suggestions?

**Comment by shannah** [comment]
My intention, in this case was to use the `errorMessage` property of the [LoginFormViewModel](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/models/LoginFormViewModel.java) to set the error message, and to add a LabelView in the login form that is bound to this property to display the error message.

**Comment by arthef** [comment]
Thank you for your help. I think I have all the basic pieces working now.

However, I cannot find any example code on the best way to handle closing Login form and opening the main app form on successful login or redisplay the login form with an error if login was unsuccessful.

In your examples you handle connection/login in the LoginFormController which seems logical. However, how to convey the login success to the main app logic to close the login form and open the main app form?

**Comment by shannah** [comment]
It uses events to notify the ApplicationController of this.

The login controller initiates a "login" on the NovaServerSession object: [here](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/controllers/LoginFormController.java#L37)

~~~~
addActionListener(login, evt->{
            evt.consume();
            session.connect(viewModel.getText(username), viewModel.getText(password));
            
        });
~~~~

The NovaServerSession has a websocket that is communicating with the server. When it determines that the login was successful, it [fires an event](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/services/NovaServerSession.java#L334):

~~~~
private void handleMessage(Message msg) {
    ...
    Form form = CN.getCurrentForm();
    Object source = form != null ? form : this;
    ...
    ActionSupport.dispatchEvent(new WelcomeViewEvent(source, ...));
    ...
}
~~~~

The `ActionSupport.dispatchEvent(ControllerEvent evt)` method will propagate the event "up" the UI hierarchy from the event source (in this case the current Form), and when it reaches the top of the UI hierarchy, if it hasn't been consumed yet, it will propagate up the controller hierarchy, e.g. starting with the FormController (in this case the LoginFormController), then to its parent controller (if not consumed), until finally it has propagated all the way up to the ApplicationController.

The ApplicationController's [actionPerformed](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/NovaTerm.java#L46) method handles this event:

~~~~
@Override
    public void actionPerformed(ControllerEvent evt) {
        if (evt.getClass() == NovaServerSession.WelcomeViewEvent.class) {
            evt.consume();
            WelcomeViewEvent welcomeEvent = (WelcomeViewEvent)evt;
            new WelcomeWindowController(this, welcomeEvent.getWelcomeViewModel()).show();
        }
        super.actionPerformed(evt);
    }
~~~~

When it receives this event, it knows that login is complete so it shows the WelcomeWindowController.  

For disconnection, the application controller is [listening](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/NovaTerm.java#L24) for changes to the "connected" property of the session.

~~~~
       session = new NovaServerSession();
        session.addPropertyChangeListener(NovaServerSession.connected, evt->{
            if (session.getBoolean(NovaServerSession.connected)) {
                
            } else {
                ToastBar.showInfoMessage("You have been disconnected");
                new LoginFormController(this).showBack();
            }
        });
~~~~


One other useful tip to understand the flow here.  This application makes use of the `Controller.addLookup(Object)` and `Controller.lookup(Class)` methods for making the Session object easily accessible to all controllers.  

In the [`init()`](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/NovaTerm.java#L21) method of the ApplicationController, it creates the session object and registers it as a lookup:

~~~~
session = new NovaServerSession();
....
this.addLookup(session);
~~~~

Then in the [LoginFormController](https://github.com/shannah/eolclient/blob/master/NovaTerm/src/ca/weblite/novaterm/controllers/LoginFormController.java#L34) we retrieve this session object via the `lookup(Class)` method:

~~~~
final NovaServerSession session = this.lookup(NovaServerSession.class);
~~~~

This works because `lookup()` will look in the current controller for any objects registered by the given class (`NovaServerSession`).  If it doesn't find one, it will search the parent controller, then its parent, until either it finds such an object, or it reaches the top of the hierarchy (the application controller) and none is found.

This way this session object is made available to all controllers in the application, without having to use a static variable.

Does this answer your question?

**Comment by arthef** [comment]
Do I need to somehow hide or destroy the LoginForm view or showing main app form is enough to replace login form with the main application form?

**Comment by shannah** [comment]
When it calls:

~~~~
new WelcomeWindowController(this, welcomeEvent.getWelcomeViewModel()).show();
~~~~

It will replace whatever form is currently showing with the view/form in the WelcomeWindowController.

The first parameter for any controller will be the "Parent" controller for it, and this establishes the context where the controller lives.  In this case I passed `this`, which means that the ApplicationController is the direct parent of the WelcomeWindowController.   This means that all other controllers on the "stack" are removed and replaced with this controller.  There will be no "back" button in the WelcomeWindowController's form because it is at the top of the controller hierarchy (except the application controller).

If this form had been passed a reference to, say, the existing LoginFormController e.g.:

~~~~
new WelcomeWindowController(loginFormController, welcomeEvent.getWelcomeViewModel()).show();
~~~~

Then the the welcome form would still effectively replace the LoginFormController on the screen, but the LoginFormController would still "live" in the navigation stack, as the parent controller of the current form.  There would be a "back" button in the WelcomeForm to return to the LoginFormController.    

In this case, it makes more sense to *not* have a back button to the LoginFormController, and instead to make the WelcomeForm the new "root" form controller, so I made the ApplicationController the parent.

**Comment by arthef** [comment]
Thank you for comprehensive explanation. It all seems to be working now.

**Comment by arthef** [comment]
This is all more or less working, except one last bit. How to do the password masking so it is not visible when a user types it in? I use similar code to `LoginFormView.java` recommended above but I do not know how to pass the option `TextField.PASSWORD` to the password input field:
```java
            form(
                    editable(true),
                    columns(1),
                    label("Login"),
                    description("Please enter the username and password to login"),
                    textField(
                            label("Username"),
                            tags(username)
                    ),
                    textField(
                            label("Password"),
                            tags(password)
                    ),
                    actions(BOTTOM_RIGHT_MENU, loginAction)
                    
            );
```

**Comment by shannah** [comment]
You can use the `PropertyViewDecoratorNode` for this.  E.g.

~~~~
textField(
                            label("Password"),
                            tags(password),
                            new PropertyViewDecoratorNode(cmp->{
                                    ((TextField)cmp).setConstraint(TextField.PASSWORD);
                                    return cmp;
                            })
                    ),
~~~~

This feature isn't well documented yet, but it can be applied to any field node, and it will take a Component as input (the component that is used for the field), and will allow you to "decorate" it.  It should return the same component usually. 

I need to create a static wrapper function for this in the UI class.

**Comment by arthef** [comment]
Thank you for responding. I am getting ClassCastException. Here is my exact code with applied your suggestion:
```kotlin
form(
        editable(true),
        columns(1),
        label("Login"),
        EntityType.description("Please enter the username and password to login"),
        textField(
                label("Username"),
                tags(LoginAction.username)
        ),
        textField(
                label("Password"),
                tags(LoginAction.password),
                PropertyViewDecoratorNode(PropertyViewDecorator { cmp: PropertyView<*> ->
                    (cmp as TextField).constraint = TextField.PASSWORD
                    cmp
                })
        ),
        textField(
                editable(false),
                enabledCondition { entity -> !entity.isEmpty(LoginAction.errorMessage) },
                //label("Login error"),
                tags(LoginAction.errorMessage)
        ),
        checkbox(
                label("Debug view"),
                tags(LoginAction.debugEnabled)
        ),
        actions(ActionCategories.BOTTOM_RIGHT_MENU, loginAction, runInTestMode, loginAndRunInTestMode)
)
```
and the exception I am getting:
```
java.lang.ClassCastException: class com.codename1.rad.propertyviews.TextFieldPropertyView cannot be cast to class com.codename1.ui.TextField (com.codename1.rad.propertyviews.TextFieldPropertyView and com.codename1.ui.TextField are in unnamed module of loader com.codename1.impl.javase.ClassPathLoader @1324409e)
	at tigase.convene.view.LoginView$1$1.decorate(LoginView.kt:55)
	at com.codename1.rad.ui.DefaultPropertyViewFactory.createPropertyView(DefaultPropertyViewFactory.java:186)
	at com.codename1.rad.ui.FieldEditor.build(FieldEditor.java:98)
	at com.codename1.rad.ui.EntityEditor$SectionEditor.buildSections(EntityEditor.java:326)
	at com.codename1.rad.ui.EntityEditor$SectionEditor.build(EntityEditor.java:355)
	at com.codename1.rad.ui.EntityEditor$SectionEditor.access$000(EntityEditor.java:304)
	at com.codename1.rad.ui.EntityEditor.buildSections(EntityEditor.java:228)
	at com.codename1.rad.ui.EntityEditor.build(EntityEditor.java:269)
	at com.codename1.rad.ui.EntityEditor.initComponent(EntityEditor.java:295)
	at com.codename1.ui.Component.initComponentImpl(Component.java:6057)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1228)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1237)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1237)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1237)
	at com.codename1.ui.Container.initComponentImpl(Container.java:1237)
	at com.codename1.ui.Form.initComponentImpl(Form.java:2365)
	at com.codename1.ui.Display.setCurrent(Display.java:1582)
	at com.codename1.ui.Form.show(Form.java:2325)
	at com.codename1.ui.Form.show(Form.java:2303)
```

**Comment by shannah** [comment]
Sorry.  My mistake.  The parameter and return type is a `PropertyView`.  You need to call `getComponent()` on it to access the `TextField` that it wraps.

e.g. 

~~~~
PropertyViewDecoratorNode(PropertyViewDecorator { cmp: PropertyView<*> ->
                    (cmp.getComponent() as TextField).constraint = TextField.PASSWORD
                    cmp
                })
~~~~

**Comment by arthef** [comment]
Works like a charm! Thank you.
