### ISSUE TITLE
@RAD property with type Integer fails

### ISSUE THREAD

**Issue by Rocketeer007** [shannah/CodeRAD#25]
With this code sample for an Entity, CodeRAD generates code that does not compile.

```
public interface MyEntity extends Entity {
    Tag myNumber= new Tag("myNumber");

    @RAD(tag = "myNumber")
    Integer getMyNumber();
    void setMyNumber(Integer myNumber);
}
```

CodeRAD generates the below wrapper class:
```
@Autogenerated
public final class MyEntityWrapper extends SimpleEntityWrapper implements MyEntity {
  public MyEntityWrapper(Entity entity) {
    super(entity);
  }

  public static MyEntity wrap(Entity entity) {
    if (entity == null) return null;if (entity instanceof MyEntity) return (MyEntity)entity;MyEntity wrapper = entity.getEntity().getWrapper(MyEntity.class);if (wrapper != null) return wrapper;wrapper = new MyEntityWrapper(entity); entity.getEntity().addWrapper(wrapper);return wrapper;
  }

  public Integer getMyNumber() {
    return (Integer)getEntity().getInteger(myNumber);
  }

  public void setMyNumber(Integer _value) {
    getEntity().setInteger(myNumber, _value);
  }
}
```

This fails to compile, because `BaseEntity` does not have a `getInteger()` method; it has `getInt()` instead.

**Comment by shannah** [comment]
I have just released v 2.0.6 of code rad which fixes this issue.

(Note: A workaround on 2.0.5 is to use `int` instead of `Integer`).

To update, you'll need to update both the coderad version in your project to 2.0.6, in two places.  You'll need to update the coderad-lib dependency, and the annotation processor dependency.
